### ISSUE TITLE
WVBrowser.Window.Frames iterate throws InvalidCastException

### ISSUE THREAD

**Issue by pjacko** [ukandrewc/Webview2.Winforms.DOM#17]
Hi there,
When iterating through the Frames the following exception:
    foreach(WVWindow frame in browser.Window.Frames) {...}

> Conversion from string "null" to type 'Integer' is not valid.
> System.InvalidCastException: Conversion from string "null" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
>    at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
>    at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
>    --- End of inner exception stack trace ---
>    at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
>    at Aimco.WV2.WVScriptHost.NewWindow(String Script, Int32 Id)
>    at Aimco.WV2.WVWindowList.VB$StateMachine_1_get_Enumerator.MoveNext()

WVBrowser.dll version is 0.0.0.824

let me know if you require any additional information.
Thanks

**Comment by ukandrewc** [comment]
It's when a frame in the list is prevented from being accessed.
I thought cross frame access was being allowed in the latest version, so I'm just looking at that.
If I can't access it then I will at least prevent that error and it will have to return null.
