### ISSUE TITLE
Fatal untrappable exception in GetFavicon

### ISSUE THREAD

**Issue by weveritt2** [ukandrewc/Webview2.Winforms.DOM#5]
System.Net.WebException
  HResult=0x80131509
  Message=An exception occurred during a WebClient request.
  Source=System
  StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Aimco.WV2.WVBrowser.GetFavicon()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Inner Exception 1:
DirectoryNotFoundException: Could not find a part of the path 'C:\APPS\VERIFIER\VeriPACK\VB.NET\Webview2.Winforms.DOM-master\Sample\bin\Debug\WV2 Test.exe.WebView2\www.rowstats.com.png'.

Source code to reproduce this exception:
Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim actl As New Aimco.WV2.WVBrowser
        actl.Dock = DockStyle.Fill

        Dim aEnvironment As Microsoft.Web.WebView2.Core.CoreWebView2Environment
        aEnvironment = Await Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(Nothing, "c:\dimaco\browser3")

        Await actl.EnsureCoreWebView2Async(aEnvironment)

        actl.Source = New Uri("http://www.rowstats.com")

        Me.Controls.Add(actl)
    End Sub

My project is compiled with VS2017 Professional as an x86 Release build.

The exception does not occur unless an Environment is passed to EnsureCoreWebView2Async - need to do this, as the application is in Program Files...

**Comment by ukandrewc** [comment]
Thanks, I'm just using the default folder for saving favicon files. I'll fix that.

**Comment by ukandrewc** [comment]
Added support for CoreWebView2Enviroment without the need for Async
```
Dim Environment = WVUtils.CreateEnvironment("", "My Folder", MyOptions)
WVBrowser.EnsureWebView2(Environment)
```
